title: Anshul Chauhan
email: anshulchauhan@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi there, I am Anshul Chauhan. I am interested in software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: anshulxyz
github_username: anshulxyz

# Build settings
plugins:
  - jekyll-feed
